export const actionCopy = {
  ACTION_INTRO: '[PLAN] 有些浪漫不靠靈感，靠你真的去做。', ACTION_MENU: '先別只是想想', ACTION_ARROW: '→',
  ACTION_DATE: '約會', ACTION_DATE_RESTAURANTS: '餐廳收藏', ACTION_DATE_RESERVATION: '訂位', ACTION_GIFT: '禮物', ACTION_GIFT_RECOMMENDATIONS: '推薦收藏', ACTION_GIFT_LOG: '紀錄', ACTION_SCHEDULE: '行程', ACTION_SCHEDULE_TODAY: '今日行程', ACTION_SCHEDULE_PLAN: '約會安排',
  PROFILE_SECTION_BASIC: '基本', PROFILE_SECTION_BASIC_COPY: '伴侶稱呼、關係開始日', PROFILE_SECTION_PREFERENCES: '喜好', PROFILE_SECTION_PREFERENCES_COPY: '還沒填，之後別說沒人提醒你', PROFILE_SECTION_DATES: '重要日', PROFILE_SECTION_DATES_COPY: '生日與那些忘了會出事的日子',
} as const;
