export const actionCopy = {
  ACTION_INTRO: '[PLAN] 將約會準備拆成可執行行動。', ACTION_MENU: 'ACTION MENU', ACTION_ARROW: '→',
  ACTION_DATE: '約會', ACTION_DATE_RESTAURANTS: '餐廳收藏', ACTION_DATE_RESERVATION: '訂位', ACTION_GIFT: '禮物', ACTION_GIFT_RECOMMENDATIONS: '推薦收藏', ACTION_GIFT_LOG: '紀錄', ACTION_SCHEDULE: '行程', ACTION_SCHEDULE_TODAY: '今日行程', ACTION_SCHEDULE_PLAN: '約會安排',
  PROFILE_SECTION_BASIC: '基本', PROFILE_SECTION_BASIC_COPY: '伴侶稱呼、關係開始日', PROFILE_SECTION_PREFERENCES: '喜好', PROFILE_SECTION_PREFERENCES_COPY: '尚未建立偏好資料', PROFILE_SECTION_DATES: '重要日', PROFILE_SECTION_DATES_COPY: '生日與自訂重要日',
} as const;
