export const commonCopy = {
  APP_TITLE: '🎮 生存攻略', APP_WAR_ROOM: '[WAR ROOM]', APP_SOS: 'SOS', APP_SOS_A11Y: '開啟 SOS 急救指南', APP_PROFILE_A11Y: '關係檔案選單', APP_RANK: 'RANK',
  NAV_HOME: 'HOME', NAV_QUEST: 'QUEST', NAV_PLAN: 'PLAN', NAV_VAULT: 'VAULT', NAV_FILE: 'FILE',
  AUTH_LOADING: '[SYSTEM] 正在讀取存檔…', AUTH_EYEBROW: '[P1] LOVEGAME I', AUTH_TITLE: '登入存檔', AUTH_DESCRIPTION: '使用 Google 帳號安全保存你的戀愛生存進度。', AUTH_FAILED: '登入失敗', AUTH_ERROR_SUBTITLE: 'SYSTEM ERROR', AUTH_RETRY_GOOGLE: '重試 Google 登入', AUTH_GOOGLE: '使用 Google 登入',
  STATUS_LOADING: '載入中…', STATUS_LOADING_COPY: '正在整理你的戀愛生存資料。', STATUS_ERROR_TITLE: '暫時無法載入', STATUS_ERROR_COPY: '請確認連線後再試一次。', STATUS_RETRY: '重試', STATUS_SYSTEM: 'SYSTEM STATUS',
  NOTIFICATION_TITLE: '戀愛生存任務提醒', NOTIFICATION_BODY: '你有一項戀愛生存任務需要查看。', NOTIFICATION_CHANNEL: '任務提醒',
  PROFILE_CENTER_TITLE: '[USER PROFILE] 個人中心', PROFILE_CLOSE_A11Y: '關閉個人中心', PROFILE_CURRENT_PLAN: '當前方案：年付 VIP 方案', PROFILE_DARK_MODE: '深色模式', PROFILE_TUTORIAL: '新手教學', PROFILE_MEMBERSHIP: '會員中心', PROFILE_ANNOUNCEMENTS: '更新公告', PROFILE_LOGOUT: '登出', PROFILE_VERSION: '生存攻略 v2.4.0 · 最新版本',
  PROFILE_TUTORIAL_TITLE: '新手教學', PROFILE_TUTORIAL_COPY: '先設定伴侶稱呼與重要日，接著完成任務，累積 EXP、Combo 與 Rank。', PROFILE_MEMBERSHIP_TITLE: '會員中心', PROFILE_MEMBERSHIP_COPY: 'VIP 方案資訊目前為展示資料；訂閱與付款功能將在後續版本開放。', PROFILE_ANNOUNCEMENTS_TITLE: '更新公告', PROFILE_ANNOUNCEMENTS_COPY: '目前版本已加入關係天數、重要日倒數與開發 Scenario。', PROFILE_DISMISS: '知道了',
} as const;
