export const dailyGameplayCopy = {
  DAILY_CRISIS_TITLE: '警報：別再拖了',
  DAILY_CRISIS_SUBTITLE: 'CRISIS DETECTED',
  DAILY_CRISIS_COPY: '重要日快到了。現在處理叫準備，最後一刻才叫災難片。',
  DAILY_ACCEPT: '好，我去面對',
  DAILY_DEFER: '讓我再逃一下',
  DAILY_ACTION_TITLE: '採取行動',
  DAILY_ACTION_SUBTITLE: 'ACTION PLAN',
  DAILY_ACTION_COPY: '完成你準備好的行動，再回來回報結果。',
  DAILY_START_REPORT: '前往回報',
  DAILY_REPORT_TITLE: '回報結果',
  DAILY_REPORT_SUBTITLE: 'REPORT',
  DAILY_REPORT_COPY: '誠實回報。系統不會罵你，但伴侶未必這麼客氣。',
  DAILY_REPORT_COMPLETE: '我真的做了',
  DAILY_REPORT_LATER: '稍後回報',
  DAILY_SAFE_TITLE: '暫時沒爆炸',
  DAILY_SAFE_SUBTITLE: 'SAFE STATE',
  DAILY_SAFE_COPY: '目前風平浪靜。趁還沒出事，做點讓人開心的事。',
  DAILY_SAFE_ACTION_TITLE: '自由行動',
  DAILY_SAFE_ACTION_DESCRIPTION: '主動傳一句關心，或規劃下一次見面，讓安全狀態持續累積。',
  DAILY_OPEN_FREE_ACTION: '開始自由行動',
  DAILY_COMPLETE_FREE_ACTION: '完成自由行動',
  DAILY_NEXT_HOOK_TITLE: '下一個目標',
  DAILY_NEXT_HOOK_DESCRIPTION: '再完成一次生存任務，就能更接近 Combo 5 的稱號解鎖。',
  DAILY_NEXT_HOOK_SUBTITLE: 'NEXT HOOK',
  DAILY_CONTINUE_NEXT_HOOK: '查看下一目標',
  DAILY_BACK_HOME: '返回首頁',
} as const;
