export const ggCopy = {
  GG_SOS_TITLE: 'SOS 急救指南',
  GG_SOS_COACH_COPY: '說錯話？忘了紀念日？立即點擊解套指南！',
  GG_SOS_CLOSE_A11Y: '關閉 SOS 急救指南',
  GG_SOS_LEVEL_ONE: 'LEVEL 1 (30%)',
  GG_SOS_LEVEL_TWO: 'LEVEL 2 (70%)',
  GG_SOS_LEVEL_THREE: 'LEVEL 3 (100%)',
  GG_SOS_DIAGNOSIS: '症狀診斷 radar（Level 1：微怒冷淡）',
  GG_SOS_DIAGNOSIS_ONE: '• 訊息回復字數極少（如：喔、嗯、隨便）',
  GG_SOS_DIAGNOSIS_TWO: '• 不主動開話題、眼神避開',
  GG_SOS_ACTION_PLAN: 'ACTION PLAN',
  GG_SOS_ACTION_ONE: '1. 立即主動發送溫柔關懷訊息，避免回覆「你怎麼了」',
  GG_SOS_ACTION_TWO: '2. 送上一份小甜點或她喜歡的飲料，主動遞水',
  GG_SOS_APOLOGY_CODE: '[APOLOGY CODE]',
  GG_SOS_APOLOGY: '「寶貝對不起，剛才是我不夠細心，沒有注意到你的心情。今天想吃點甜的嗎？我買給你！」',
  GG_SOS_QUICK_ACTIONS: 'QUICK ACTIONS',
  GG_SOS_DRINK_DELIVERY: '訂飲料快送',
  GG_SOS_APOLOGY_LINES: '道歉盒句',
} as const;
