export const ggCopy = {
  GG_SOS_TITLE: 'SOS 急救指南',
  GG_SOS_COACH_COPY: '說錯話？忘了紀念日？立即點擊解套指南！',
  GG_SOS_CLOSE_A11Y: '關閉 SOS 急救指南',
  GG_SOS_LEVEL_ONE: 'LEVEL 1 (30%)',
  GG_SOS_LEVEL_TWO: 'LEVEL 2 (70%)',
  GG_SOS_LEVEL_THREE: 'LEVEL 3 (100%)',
  GG_SOS_DIAGNOSIS: '症狀診斷 radar（Level 1：微怒冷淡）',
  GG_SOS_DIAGNOSIS_ONE: '• 訊息回復字數極少（如：喔、嗯、隨便）',
  GG_SOS_DIAGNOSIS_TWO: '• 不主動開話題、眼神避開',
  GG_SOS_ACTION_PLAN: 'ACTION PLAN',
  GG_SOS_ACTION_ONE: '1. 立即主動發送溫柔關懷訊息，避免回覆「你怎麼了」',
  GG_SOS_ACTION_TWO: '2. 送上一份小甜點或她喜歡的飲料，主動遞水',
  GG_SOS_APOLOGY_CODE: '[APOLOGY CODE]',
  GG_SOS_COPY_A11Y: '複製道歉訊息',
  GG_SOS_COPIED: '已複製',
  GG_SOS_APOLOGY: '「寶貝對不起，剛才是我不夠細心，沒有注意到你的心情。今天想吃點甜的嗎？我買給你！」',
  GG_SOS_QUICK_ACTIONS: 'QUICK ACTIONS',
  GG_SOS_DRINK_DELIVERY: '訂飲料快送',
  GG_SOS_APOLOGY_LINES: '道歉盒句',
  GG_SOS_LEVEL_TWO_DIAGNOSIS: '症狀診斷 radar（Level 2：明顯不滿）',
  GG_SOS_LEVEL_TWO_DIAGNOSIS_ONE: '• 對方明確表示不舒服、失望，或只想結束對話',
  GG_SOS_LEVEL_TWO_DIAGNOSIS_TWO: '• 已讀久未回、取消原本安排，且不願解釋原因',
  GG_SOS_LEVEL_TWO_ACTION_ONE: '1. 先承認造成的影響，不急著辯解或要求立刻原諒',
  GG_SOS_LEVEL_TWO_ACTION_TWO: '2. 提出具體補救與可談時間，並準時做到你答應的事',
  GG_SOS_LEVEL_TWO_APOLOGY: '「我知道剛剛的做法讓你失望，這不是你需要一直提醒我的事。你現在想先休息也沒關係；等你願意時，我想好好聽你說，並把我答應的補救做到。」',
  GG_SOS_LEVEL_TWO_QUICK_ONE: '安排補救時間',
  GG_SOS_LEVEL_TWO_QUICK_TWO: '整理道歉重點',
  GG_SOS_LEVEL_THREE_DIAGNOSIS: '症狀診斷 radar（Level 3：高風險衝突）',
  GG_SOS_LEVEL_THREE_DIAGNOSIS_ONE: '• 對方要求空間、封鎖聯絡，或明確表示暫時不想見面',
  GG_SOS_LEVEL_THREE_DIAGNOSIS_TWO: '• 對話已出現人身攻擊、翻舊帳，情緒持續升高',
  GG_SOS_LEVEL_THREE_ACTION_ONE: '1. 立刻停止連環訊息、追問與爭辯，先讓雙方情緒降溫',
  GG_SOS_LEVEL_THREE_ACTION_TWO: '2. 尊重對方界線；等對方願意後，再以傾聽和具體改變討論',
  GG_SOS_LEVEL_THREE_APOLOGY: '「我看到我們現在都很難受，我不想再用情緒傷害你。我會先停下來、尊重你想要的空間；等你願意談時，我會好好聽，不再急著反駁。」',
  GG_SOS_LEVEL_THREE_QUICK_ONE: '停止訊息轟炸',
  GG_SOS_LEVEL_THREE_QUICK_TWO: '建立冷靜計畫',
  REBIRTH_EYEBROW: '[REBIRTH AVAILABLE]',
  REBIRTH_TITLE: '你 GG 了，但還沒被系統刪檔。',
  REBIRTH_COPY: '先寫下你學到什麼。這次不能空手復活，系統記得你。',
  REBIRTH_OATH_LABEL: '這一輪學到什麼',
  REBIRTH_OATH_PLACEHOLDER: '下次不會等到最後一天才開始做人',
  REBIRTH_PREVIOUS_OATH_TITLE: '上次你是這樣宣誓的',
  REBIRTH_PREVIOUS_OATH_COPY: '「{oath}」\n結果又 GG 了。這次寫點真的會做的。',
  REBIRTH_EFFECT: 'Rank 回到 -5，Combo 歸零；EXP 與黑歷史照樣留下。',
  REBIRTH_CONFIRM: '立下誓言，重新做人',
  REBIRTH_HISTORY_TITLE: '上一輪已封存',
  REBIRTH_HISTORY_COPY: '死因：{cause}｜最高 Rank：{rank}',
  RUN_HISTORY_TITLE: '輪迴紀錄',
  RUN_HISTORY_COPY: 'Run #{number}｜最高 Rank：{rank}｜成功 {success}｜遲到 {late}｜失敗 {fail}',
} as const;
