export const homeCopy = {
  HOME_PLAYER_LABEL: 'P1/P2',
  HOME_STAGE_LABEL: 'STAGE',
  HOME_COUNTDOWN_SUBTITLE: 'DATE COUNTDOWN',
  HOME_REMAIN_LABEL: 'REMAIN',
  HOME_ADVICE_LABEL: '[ADVICE]',
  HOME_IMPORTANT_DATE_ADVICE: '{label}倒數 {days} DAYS。現在不動，未來的你會想把手機丟掉。',
  HOME_NO_IMPORTANT_DATE: '重要日還沒登錄。未來的你暫時逃過一劫。',
  HOME_EXP_LABEL: 'EXP',
  HOME_COMBO_LABEL: 'COMBO',
  HOME_RANK_LABEL: 'RANK',
  HOME_OPEN_MISSIONS: '查看任務',
  HOME_TODAY_QUEST_TITLE: '今天還有一點良心',
  HOME_TODAY_QUEST_COPY: '去翻張卡吧。只花一點點力氣，關係不用等到壞掉才維修。',
  HOME_GO_TO_QUESTS: '去做點人事',
} as const;
